plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.148'
    id 'idea'
}

version = mod_version
group = mod_group_id
base { archivesName = mod_id }

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll(
                '--mod', project.mod_id,
                '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
        }
    }

    mods {
        smoothframe {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources.srcDir('src/generated/resources')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

processResources {
    var replaceProperties = [
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version: neo_version,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_version: mod_version,
        mod_authors: mod_authors,
        mod_description: mod_description
    ]

    inputs.properties replaceProperties

    from('src/main/templates/META-INF/neoforge.mods.toml') {
        into 'META-INF'
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes(
            'Specification-Title': mod_name,
            'Specification-Version': mod_version,
            'Implementation-Title': mod_name,
            'Implementation-Version': mod_version
        )
    }
}
